# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clac.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from tokenize import Number
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(10, 100, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(80, 100, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(150, 100, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_3.setObjectName("btn_3")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(220, 100, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(150, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(220, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_6.setObjectName("btn_6")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(80, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(10, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(150, 240, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_9.setObjectName("btn_9")
        self.btn_10 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_10.setGeometry(QtCore.QRect(220, 240, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_10.setFont(font)
        self.btn_10.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_10.setObjectName("btn_10")
        self.btn_11 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_11.setGeometry(QtCore.QRect(80, 240, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_11.setFont(font)
        self.btn_11.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_11.setObjectName("btn_11")
        self.btn_12 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_12.setGeometry(QtCore.QRect(10, 240, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_12.setFont(font)
        self.btn_12.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_12.setObjectName("btn_12")
        self.btn_13 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_13.setGeometry(QtCore.QRect(150, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_13.setFont(font)
        self.btn_13.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_13.setObjectName("btn_13")
        self.btn_14 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_14.setGeometry(QtCore.QRect(220, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_14.setFont(font)
        self.btn_14.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_14.setObjectName("btn_14")
        self.btn_15 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_15.setGeometry(QtCore.QRect(80, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_15.setFont(font)
        self.btn_15.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_15.setObjectName("btn_15")
        self.btn_16 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_16.setGeometry(QtCore.QRect(10, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_16.setFont(font)
        self.btn_16.setStyleSheet("background-color: rgb(131, 131, 131);\n"
"color: rgb(255, 255, 255);")
        self.btn_16.setObjectName("btn_16")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(12, 30, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(72, 72, 72);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn_click()
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_1.setText(_translate("MainWindow", "C"))
        self.btn_2.setText(_translate("MainWindow", "*"))
        self.btn_3.setText(_translate("MainWindow", "/"))
        self.btn_4.setText(_translate("MainWindow", "0"))
        self.btn_5.setText(_translate("MainWindow", "9"))
        self.btn_6.setText(_translate("MainWindow", "-"))
        self.btn_7.setText(_translate("MainWindow", "8"))
        self.btn_8.setText(_translate("MainWindow", "7"))
        self.btn_9.setText(_translate("MainWindow", "6"))
        self.btn_10.setText(_translate("MainWindow", "+"))
        self.btn_11.setText(_translate("MainWindow", "5"))
        self.btn_12.setText(_translate("MainWindow", "4"))
        self.btn_13.setText(_translate("MainWindow", "3"))
        self.btn_14.setText(_translate("MainWindow", "="))
        self.btn_15.setText(_translate("MainWindow", "2"))
        self.btn_16.setText(_translate("MainWindow", "1"))
    def btn_click(self):
        self.btn_16.clicked.connect(lambda:self.write_number(self.btn_16.text()))
        self.btn_4.clicked.connect(lambda:self.write_number(self.btn_4.text()))
        self.btn_15.clicked.connect(lambda:self.write_number(self.btn_15.text()))
        self.btn_13.clicked.connect(lambda:self.write_number(self.btn_13.text()))
        self.btn_12.clicked.connect(lambda:self.write_number(self.btn_12.text()))
        self.btn_11.clicked.connect(lambda:self.write_number(self.btn_11.text()))
        self.btn_10.clicked.connect(lambda:self.write_number(self.btn_10.text()))
        self.btn_9.clicked.connect(lambda:self.write_number(self.btn_9.text()))
        self.btn_8.clicked.connect(lambda:self.write_number(self.btn_8.text()))
        self.btn_7.clicked.connect(lambda:self.write_number(self.btn_7.text()))
        self.btn_6.clicked.connect(lambda:self.write_number(self.btn_6.text()))
        self.btn_5.clicked.connect(lambda:self.write_number(self.btn_5.text()))
        self.btn_3.clicked.connect(lambda:self.write_number(self.btn_3.text()))
        self.btn_2.clicked.connect(lambda:self.write_number(self.btn_2.text()))
        self.btn_14.clicked.connect(self.results)
        self.lineEdit.setClearButtonEnabled(True)
    

        
    def write_number(self,number):
        self.lineEdit.setText(self.lineEdit.text()+ number) 
        
    
    def results(self):
        res= eval(self.lineEdit.text())
        self.lineEdit.setText(str(res))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
